### ISSUE TITLE
fps limiter?

### ISSUE THREAD

**Issue by EnAppelsin** [EnAppelsin/SHARCarRandomiser#2]
Apparently the frame limiter doesn't work properly or something?

**Comment by jakeandreoli** [comment]
Is there any other details? Because I can't imagine how the FPS limiter would affect these scripts.

**Comment by EnAppelsin** [comment]
I was also unsure how it would affect it, it was a comment from a streamer. After more discussions it seems more likely they either accidentally disabled it or just wasn't used to certain cars with the high FPS they had set. I am going to assume it's not a bug unless I hear more reports.
